.\"
.\" sc_wartsfilter.1
.\"
.\" Author: Matthew Luckie <mjl@luckie.org.nz>
.\"
.\" Copyright (c) 2019 University of Waikato
.\" Copyright (c) 2022 Matthew Luckie
.\"                    All rights reserved
.\"
.\" $Id: sc_wartsfilter.1,v 1.5 2023/03/10 05:01:22 mjl Exp $
.\"
.Dd March 10, 2023
.Dt SC_WARTSFILTER 1
.Os
.Sh NAME
.Nm sc_wartsfilter
.Nd select specific records from a warts file
.Sh SYNOPSIS
.Nm
.Bk -words
.Op Fl a Ar address
.Op Fl i Ar input-file
.Op Fl o Ar output-file
.Op Fl O Ar option
.Op Fl t Ar record-type
.Ek
.\""""""""""""
.Sh DESCRIPTION
The
.Nm
utility selects specific records from
.Xr warts 5
input, and outputs those records.
The supported options to
.Nm
are as follows:
.Bl -tag -width Ds
.It Fl a Ar address
specifies an address or prefix of interest.
If there are multiple addresses or prefixes of interest, these can
be specified with additional -a options.
.It Fl i Ar input-file
specifies the input warts file to process.
If - is specified, then
.Nm
will read from stdin.
.It Fl o Ar output-file
specifies the output warts file to write records to.
If - is specified, then
.Nm
will write to stdout.
.It Fl O Ar option
allows the behavior of
.Nm
to be further tailored.
The current choices for this option are:
.Bl -dash -offset 2n -compact -width 1n
.It
.Sy check-hops:
Check if an address of an intermediate hop in a trace or tracelb object
matches.
.El
.It Fl t Ar record-type
specifies a record type of interest.
The current choices for this option are:
.Bl -dash -offset 2n -compact -width 1n
.It
.Sy dealias
.It
.Sy ping
.It
.Sy tbit
.It
.Sy trace
.It
.Sy tracelb
.El
.El
.\""""""""""""
.Sh EXAMPLES
The command:
.Pp
.in +.3i
sc_wartsfilter -i input.warts -o output.warts -a 192.0.2.5 -a 192.0.2.6
.in -.3i
.Pp
outputs all warts records with a destination address of 192.0.2.5 or
192.0.2.6 from input.warts into output.warts.
.Pp
The command:
.Pp
.in +.3i
sc_wartsfilter -i input.warts -o output.warts -a 2001:db8::/32
.in -.3i
.Pp
outputs all warts records with a destination address within the
2001:db8::/32 prefix into output.warts.
.Pp
The command:
.Pp
.in +.3i
gzcat input.warts.gz | sc_wartsfilter -t ping | sc_warts2json
.in -.3i
.Pp
selects all ping records from a decompressed input file and and pipes
them to sc_warts2json.
.Pp
.\""""""""""""
.Sh SEE ALSO
.Xr scamper 1 ,
.Xr sc_warts2json 1 ,
.Xr sc_wartsdump 1 ,
.Xr warts 5
.\""""""""""""
.Sh AUTHORS
.Nm
was written by Matthew Luckie.
